#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php$")

for FILE in $STAGED_FILES
do
        php -l -d display_errors=0 "$FILE"
        if [ $? != 0 ]
        then
                echo "Fix syntax error before commit"
                exit 1
        else
                phpcs --colors "$FILE"
                if [ $? != 0 ]
                then
                        echo "Fix the error before committing"
                        echo "use phpcbf for automatic fix"
                        exit 1
                fi
        fi
done

exit $?
